### ISSUE TITLE
Add Electric Blue data parser

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/ocean-data-parser#11]
# Add a Electric Blue parser 
- [x] Add module
- [x] Get test files
- [x] Create parser
- [x] Create test in pytest

**Comment by zmonteith** [comment]
I provided the test files in the email thread, but I'll included them here in the interest of completeness.
[log_2021-07-01 093218.csv](https://github.com/HakaiInstitute/ocean-data-parser/files/9636509/log_2021-07-01.093218.csv)
[04E4 DB00 2E39 0B-20210701 174652.csv](https://github.com/HakaiInstitute/ocean-data-parser/files/9636510/04E4.DB00.2E39.0B-20210701.174652.csv)

**Comment by JessyBarrette** [comment]
Thanks @zmonteith the files were added to the package as test files.

**Comment by JessyBarrette** [comment]
The electric blue parser for the dat files is now available within the development branch
