### ISSUE TITLE
Add Star Oddi data parser

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/ocean-data-parser#12]
# Add a star-Oddi parser 
- [x] Add module
- [x] Get test files
- [x] Create parser
- [x] Create test in pytest
- [x] Map fields as close as possible to cf
- [x] Add cf terms

**Comment by JessyBarrette** [comment]
This data has been used by DFO PBS

**Comment by zmonteith** [comment]
attaching the star-oddi example data files to this issue. File is a plain text file, but extension type was originally .DAT. Extension changed to .txt to allow for loading here.
[2S11412.txt](https://github.com/HakaiInstitute/ocean-data-parser/files/9636525/2S11412.txt)

**Comment by JessyBarrette** [comment]
Thanks @zmonteith the files were added to the package as test files.
